// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantePro.Infrastructure.Persistence.Contexts;

#nullable disable

namespace RestaurantePro.Infrastructure.Migrations.ProveedoresDb
{
    [DbContext(typeof(ProveedoresDbContext))]
    partial class ProveedoresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantePro.Domain.Proveedores.Entities.ContactoProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_ContactosProveedores_Nombre");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("IX_ContactosProveedores_ProveedorId");

                    b.ToTable("ContactosProveedores", "Proveedores");
                });

            modelBuilder.Entity("RestaurantePro.Domain.Proveedores.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiasCredito")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("InformacionBancaria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RUT");

                    b.Property<DateTime?>("UltimaOrden")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Proveedores_Nombre");

                    b.HasIndex("RFC")
                        .IsUnique()
                        .HasDatabaseName("IX_Proveedores_RUT");

                    b.ToTable("Proveedores", "Proveedores");
                });

            modelBuilder.Entity("RestaurantePro.Domain.Proveedores.Entities.ContactoProveedor", b =>
                {
                    b.HasOne("RestaurantePro.Domain.Proveedores.Entities.Proveedor", null)
                        .WithMany("Contactos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RestaurantePro.Domain.Core.SharedKernel.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ContactoProveedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("ContactoProveedorId");

                            b1.ToTable("ContactosProveedores", "Proveedores");

                            b1.WithOwner()
                                .HasForeignKey("ContactoProveedorId");
                        });

                    b.OwnsOne("RestaurantePro.Domain.Core.SharedKernel.ValueObjects.PhoneNumber", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("ContactoProveedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Telefono");

                            b1.HasKey("ContactoProveedorId");

                            b1.ToTable("ContactosProveedores", "Proveedores");

                            b1.WithOwner()
                                .HasForeignKey("ContactoProveedorId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantePro.Domain.Proveedores.Entities.Proveedor", b =>
                {
                    b.OwnsOne("RestaurantePro.Domain.Core.SharedKernel.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ProveedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("ProveedorId");

                            b1.ToTable("Proveedores", "Proveedores");

                            b1.WithOwner()
                                .HasForeignKey("ProveedorId");
                        });

                    b.OwnsOne("RestaurantePro.Domain.Core.SharedKernel.ValueObjects.PhoneNumber", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("ProveedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Telefono");

                            b1.HasKey("ProveedorId");

                            b1.ToTable("Proveedores", "Proveedores");

                            b1.WithOwner()
                                .HasForeignKey("ProveedorId");
                        });

                    b.OwnsMany("RestaurantePro.Domain.Proveedores.ValueObjects.ProveedorCategoria", "Categorias", b1 =>
                        {
                            b1.Property<Guid>("ProveedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Categoria")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<bool>("EsProveedorPrincipal")
                                .HasColumnType("bit");

                            b1.Property<decimal>("PorcentajeDescuento")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("ProveedorId", "Categoria");

                            b1.ToTable("ProveedorCategorias", "Proveedores");

                            b1.WithOwner()
                                .HasForeignKey("ProveedorId");
                        });

                    b.Navigation("Categorias");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantePro.Domain.Proveedores.Entities.Proveedor", b =>
                {
                    b.Navigation("Contactos");
                });
#pragma warning restore 612, 618
        }
    }
}
