<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Backend\RestaurantePro.Api\RestaurantePro.API.csproj" />
    <ProjectReference Include="..\..\Backend\RestaurantePro.Infrastructure\RestaurantePro.Infrastructure.csproj" />
  </ItemGroup>

</Project>
